"""The gateway WebSocket session: frame builders and parsers, timing policies, and the transport seam."""

from __future__ import annotations

from pyagorartc.session.messages import (
    BROWSER_USER_AGENT,
    ErrorInfo,
    FrameType,
    GatewayFrame,
    JoinResult,
    Notification,
    P2PLost,
    P2POk,
    RtpCapabilities,
    UserEvent,
    build_join,
    build_leave,
    build_ping,
    build_renew_token,
    build_set_client_role,
    build_subscribe,
    build_unsubscribe,
    describe_frame,
    encode_frame,
    existing_streams_from_join,
    is_quit,
    lacks_payload_type,
    new_process_id,
    new_request_id,
    parse_error,
    parse_frame,
    parse_join_result,
    parse_notification,
    parse_p2p_lost,
    parse_p2p_ok,
    parse_remote_stream,
    parse_rtp_capability_change,
    parse_user_event,
)
from pyagorartc.session.recovery import Keepalive, PeerRecovery, RenewDebounce
from pyagorartc.session.session import AgoraSession, Spawn
from pyagorartc.session.transport import GatewayConnection, GatewayTransport, WebsocketsConnection, WebsocketsTransport

__all__ = [
    "BROWSER_USER_AGENT",
    "AgoraSession",
    "ErrorInfo",
    "FrameType",
    "GatewayConnection",
    "GatewayFrame",
    "GatewayTransport",
    "JoinResult",
    "Keepalive",
    "Notification",
    "P2PLost",
    "P2POk",
    "PeerRecovery",
    "RenewDebounce",
    "RtpCapabilities",
    "Spawn",
    "UserEvent",
    "WebsocketsConnection",
    "WebsocketsTransport",
    "build_join",
    "build_leave",
    "build_ping",
    "build_renew_token",
    "build_set_client_role",
    "build_subscribe",
    "build_unsubscribe",
    "describe_frame",
    "encode_frame",
    "existing_streams_from_join",
    "is_quit",
    "lacks_payload_type",
    "new_process_id",
    "new_request_id",
    "parse_error",
    "parse_frame",
    "parse_join_result",
    "parse_notification",
    "parse_p2p_lost",
    "parse_p2p_ok",
    "parse_remote_stream",
    "parse_rtp_capability_change",
    "parse_user_event",
]
